import Header from '@/component/header/header'
import './bootstrap.css'
import './fonts.css'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/component/footer/footer'
import { StrictMode } from 'react'
import { Provider } from 'react-redux'
import { store } from '@/redux/store'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // <StrictMode>
    //   <Provider store={store}>
          <html lang="en">
            <body className="page-wrapper">
              <Header />
              {children}
              <Footer />
            </body>
          </html>
    //   </Provider>
    // </StrictMode>
  )
}
